# -*- coding: utf-8 -*-
"""2015312904_KwonJoonWoo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17xv7L8rVnmis1k-5T5-spSznJKeDbCZH
"""

import nltk
import json
from nltk.tokenize import word_tokenize
from google.colab import files
from sklearn.feature_extraction.text import TfidfVectorizer

# Settings 1
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

path = '/content/drive/My Drive/test/bbc_articles.json'
with open(path,'r') as f:
  json_data = json.load(f)

keylist = json_data.keys()

newpath = '/content/drive/My Drive/test/2015312904_KwonJoonWoo_TFIDF.txt'
f = open(newpath,'w')

# Settings 2
list=[]
sample_list=['VB','VBD','VBG','VBN','VBP','VBZ','NN','NNS','NNP','NNPS']
temp_article = []
real_article = []

# Combining all 300 articles in one list
for i in keylist:
  for temp in json_data[i]:
    temp_article.append(''.join(temp))
print('Original: {}'.format(temp_article))

# Check if tags are in sample list
for temp in temp_article:
  tokens = word_tokenize(temp)
  tagged_tokens = nltk.pos_tag(tokens)
  real_article.append(' '.join([i[0] for i in tagged_tokens if i[1] in sample_list]))
print('After Tags Verification: {}'.format(real_article))

# fit_transform
tfidfvect_my = TfidfVectorizer()
tfidfvect_my.fit_transform(real_article)
print('---------------------------------------------------------')

# Displaying the result
for i in keylist:
  num=1
  for temp in json_data[i]:
    tokens = word_tokenize(temp)
    tagged_tokens = nltk.pos_tag(tokens)
    new_num =str(num)
    f.write('('+i+new_num+')'+'\n')
    num += 1
  
  # Calculating TF-IDF
    for (word,pos) in tagged_tokens:
      if pos in sample_list:
        list.append(word)
    new_list =[' '.join(list)]
    TF_IDF = tfidfvect_my.transform(new_list).toarray().tolist()

  # Display format
    for first in TF_IDF:
      for second in first:
        f.write('{}\t'.format(second))

  # Initialization
    del list[:]
    del new_list[:]
    f.write('\n')
    f.write('\n')

print('*** All work is done! ***')

from google.colab import drive
drive.mount('/content/drive')